name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -m pytest -q
      - name: Smoke normalize sample data
        run: |
          python -m interest_group_analysis.data_processing.process_and_normalize --raw-dir data/sample --out-dir data/normalized/sample --clean
      - name: Run mention extraction (sample)
        run: |
          python -m interest_group_analysis.data_processing.mention_extraction --source-dir data/sample --interest-csv data/sample/interest_groups.csv --out-dir data/processed/sample --no-resume
